//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACommunicator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACommunicatorEntities : DbContext
    {
        public ACommunicatorEntities()
            : base("name=ACommunicatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUser> AUsers { get; set; }
        public virtual DbSet<EndUser> EndUsers { get; set; }
        public virtual DbSet<Option> Options { get; set; }
    }
}
