//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACommunicator
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EndUser()
        {
            this.AUsers = new HashSet<AUser>();
            this.Options = new HashSet<Option>();
        }

        /// <summary>
        /// Copy constructor => creates copy of object of type EndUser
        /// </summary>
        /// <param name="endUser">object to copy</param>
        public EndUser(EndUser endUser)
        {
            this.PicturePath = endUser.PicturePath;
            this.Options = endUser.Options;
            this.AUsers = endUser.AUsers;
            this.Id = endUser.Id;
            this.Name = endUser.Name;
            this.Username = endUser.Username;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string PicturePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUser> AUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Option> Options { get; set; }
    }
}
